### ISSUE TITLE
No one is using `Shape.backprop_ith_arg`. Why? Remove it.

### ISSUE THREAD

**Issue by lukstafi** [ahrefs/ocannl#256]
`backprop_ith_arg` swaps the given RHS projection with the LHS projection.

**Comment by mikhailazaryan** [comment]
I removed all occurrences of `Shape.backprop_ith_arg` in the PR #257. Should it be done just like this?

**Comment by lukstafi** [comment]
The syntax extension `%cd`, e.g. `Ppx_cd.project_p_slot`, selects the right projection, regardless of whether it's for backpropagation. The function would still be helpful for manually constructing the backprop code.

**Comment by mikhailazaryan** [comment]
Alright! Is this project actually open for PRs and other contributors?

**Comment by lukstafi** [comment]
I welcome contributions. For example, I would appreciate someone familiar with LLVM writing an `llvm` backend. It would be a straightforward translation of the `gccjit` backend to `llvm` -- targeting CPU, plus configuration of the LLVM optimizer.

**Comment by lukstafi** [comment]
@mikhailazaryan I'm interested in developing the LLVM backend too so let me know if you decide to pick it up. Tutorial: https://github.com/arbipher/llvm-ocaml-tutorial
